"""spatialx-transform package."""

from __future__ import annotations

try:
    from ._version import __version__
except ImportError:  # pragma: no cover - generated by setuptools-scm at build time
    __version__ = "0.0.0"

from .point import Point, PointList
from .transforms import (
    Transformation,
    TransformationType,
    Identity,
    Affine,
    TPS,
    Composed,
    Square,
)
from .params import (
    AffineParams,
    TransformationParams,
    ComposedParams,
    TPSParams,
)

from .warp import warp_transform
from .exception import (
    WarpError,
    OpenZarrError,
    CreateOutputError,
    InvalidImageDimensionError,
    BuildChunkSegmentError,
    InvalidTransformError,
    ChunkProcessingError,
    DegenerateTriangleError,
)

__all__ = [
    "__version__",
    "Point",
    "PointList",
    "Transformation",
    "TransformationType",
    "Identity",
    "Affine",
    "TPS",
    "Composed",
    "Square",
    "AffineParams",
    "TransformationParams",
    "ComposedParams",
    "TPSParams",
    "warp_transform",
    "WarpError",
    "OpenZarrError",
    "CreateOutputError",
    "InvalidImageDimensionError",
    "BuildChunkSegmentError",
    "InvalidTransformError",
    "ChunkProcessingError",
    "DegenerateTriangleError",
]


def main() -> None:
    """Entry point that prints version info."""
    print(f"spatialx-transform v{__version__}")
