"""spatialx-transform package."""

from __future__ import annotations

try:
    from ._version import __version__
except ImportError:  # pragma: no cover - generated by setuptools-scm at build time
    __version__ = "0.0.0"


def main() -> None:
    """Entry point that prints a greeting."""
    print("spatialx-transform")
